version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASS
    ports:
      - $DOCKER_PORT_DB:$MONGODB_PORT
    volumes:
      - mongodb:/data/db
  app:
    depends_on:
      - mongodb
    restart: unless-stopped
    build: .
    ports:
      - $DOCKER_PORT_HTTP:$APP_PORT_HTTP
      - $DOCKER_PORT_HTTPS:$APP_PORT_HTTPS
    environment:
      - PORT_HTTP=$APP_PORT_HTTP
      - PORT_HTTPS=$APP_PORT_HTTPS
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DB
      - DB_USER=$MONGODB_USER
      - DB_PASS=$MONGODB_PASS
      - DB_PORT=$DOCKER_PORT_DB
volumes:
  mongodb: